In [1]:
import pandas as pd
import os
import pathlib

### Open csv dir and load all csv

In [2]:
def load_data_csv(path):
    if not os.path.exists(path):
        raise ValueError("Error: path does not exist")
    
    try:
        for root, _, files in os.walk(path):
            for f in files:
                if f.endswith(".csv"):
                    yield os.path.join(root, f)
    except Exception as e:
        raise ValueError(f"Error loading files due to: {e}")

In [3]:
try:
    all_dfs = []
    for csv_file in load_data_csv("./csv_dir"):  # assuming you are calling method from WebScraper
        try:
            df = pd.read_csv(csv_file, on_bad_lines='skip')  # Skip malformed rows
            df.replace("", pd.NA, inplace=True)  # Treat empty strings as missing
            df.dropna(inplace=True)  # Remove rows with missing values
            all_dfs.append(df)
        except Exception as inner_e:
            print(f"⚠️ Skipping file {csv_file} due to read error: {inner_e}")
    
    if not all_dfs:
        print("⚠️ No valid CSV files found or all files failed.")
        ads = pd.DataFrame()
    else:
        ads = pd.concat(all_dfs, ignore_index=True)
        print(ads.head())

except Exception as e:
    print(f"❌ Error occurred during dataset loading: {e}")

                                               title  \
0             Senior Front End Developer / Team Lead
1                           Senior ReactJs Developer
2  Full Stack Software Developer (MERN Stack) (RE...
3                          Full Stack MERN Developer
4                               Junior Web Developer

                                      company location  \
0  Compass Training and Consultancy Pvt. Ltd.   Lahore
1                    Physicians Revenue Group   Lahore
2                                          NR   Lahore
3                                   Technisia   Lahore
4                          Xtraordinary Minds   Lahore

                            salary  \
0  Rs 375,000 - Rs 425,000 a month
1                    Not specified
2   Rs 20,000 - Rs 100,000 a month
3                    Not specified
4                        Full-time

                                         description  \
0  4+ years of professional experience as a front...
1  Review code, enforce standards, and mentor jun...
2  Tailwind CSS / Material-UI / Bootstrap.\nWork ...
3  Ability to manage and lead a team of developer...
4  Collaborate with frontend developers to implem...

                                                 url
0  https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1  https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2  https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3  https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4  https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...

#### Clean dataset

In [ ]:
ads

,title,company,location,salary,description,url
0,Senior Front End Developer / Team Lead,Compass Training and Consultancy Pvt. Ltd.,Lahore,"Rs 375,000 - Rs 425,000 a month",4+ years of professional experience as a front...,https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1,Senior ReactJs Developer,Physicians Revenue Group,Lahore,Not specified,"Review code, enforce standards, and mentor jun...",https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2,Full Stack Software Developer (MERN Stack) (RE...,NR,Lahore,"Rs 20,000 - Rs 100,000 a month",Tailwind CSS / Material-UI / Bootstrap.\nWork ...,https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3,Full Stack MERN Developer,Technisia,Lahore,Not specified,Ability to manage and lead a team of developer...,https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4,Junior Web Developer,Xtraordinary Minds,Lahore,Full-time,Collaborate with frontend developers to implem...,https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...
...,...,...,...,...,...,...
219,Architect,Urban Tech,Lahore,"Rs 50,000 - Rs 60,000 a month","Deliver compelling project presentations, clea...",https://pk.indeed.com/rc/clk?jk=60497459c7dff0...
220,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
221,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...
222,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
223,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...

In [9]:
ads.drop_duplicates(subset=['title', 'company', 'location', 'description','url'], inplace=True)
ads.dropna(inplace=True)
ads

,title,company,location,salary,description,url
0,Senior Front End Developer / Team Lead,Compass Training and Consultancy Pvt. Ltd.,Lahore,"Rs 375,000 - Rs 425,000 a month",4+ years of professional experience as a front...,https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1,Senior ReactJs Developer,Physicians Revenue Group,Lahore,Not specified,"Review code, enforce standards, and mentor jun...",https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2,Full Stack Software Developer (MERN Stack) (RE...,NR,Lahore,"Rs 20,000 - Rs 100,000 a month",Tailwind CSS / Material-UI / Bootstrap.\nWork ...,https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3,Full Stack MERN Developer,Technisia,Lahore,Not specified,Ability to manage and lead a team of developer...,https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4,Junior Web Developer,Xtraordinary Minds,Lahore,Full-time,Collaborate with frontend developers to implem...,https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...
...,...,...,...,...,...,...
219,Architect,Urban Tech,Lahore,"Rs 50,000 - Rs 60,000 a month","Deliver compelling project presentations, clea...",https://pk.indeed.com/rc/clk?jk=60497459c7dff0...
220,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
221,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...
222,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
223,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...

### Markdown

In [12]:
df

,title,company,location,salary,description,url
0,Python Developer,PureLogics,Lahore,"Rs 200,000 - Rs 300,000 a month",The ideal candidate will have a solid backgrou...,https://pk.indeed.com/rc/clk?jk=60db15ff401d09...
1,Python Intern,FiveRivers Technologies,Lahore,Not specified,Assist in the development and maintenance of P...,https://pk.indeed.com/rc/clk?jk=7dbd58d33afb2b...
2,Data Analyst,Get Appoint,Lahore,"Rs 100,000 - Rs 170,000 a month","Collect, process, and analyze large datasets t...",https://pk.indeed.com/rc/clk?jk=479b32131f29d3...
3,Python Developer Intern - AI Bot (Whisper + Vo...,"VoIPmen Private Limited, Lahore",Lahore,"Rs 30,000 - Rs 40,000 a month","VoipMen is building a cutting-edge, real-time ...",https://pk.indeed.com/rc/clk?jk=9876d37fe418cb...
4,Python Developer,Dejure Technologies,Lahore,"Rs 100,000 - Rs 150,000 a month","In this role, you will help develop, test, and...",https://pk.indeed.com/rc/clk?jk=f112848d1c115c...
5,Python Developer,Stackup Solutions,Lahore,Not specified,The ideal candidate will be responsible for bu...,https://pk.indeed.com/rc/clk?jk=fb9e4637cd70e1...
6,Python Developer,Broadstone technologies,Lahore,"Rs 50,000 - Rs 150,000 a month",Strong grasp of algorithms and core foundation...,https://pk.indeed.com/rc/clk?jk=e47c8442062585...
7,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Design, develop, and maintain backend servic...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
8,Software Development Internship,Prosigns,Lahore,"Rs 15,000 - Rs 30,000 a month","We specialize in digital transformation, cover...",https://pk.indeed.com/rc/clk?jk=0fc9dbd1b41cf9...
9,Business Intelligence (Power BI),HR Professional,Lahore,"Rs 200,000 - Rs 295,000 a month",We're looking for a Business Intelligence (BI)...,https://pk.indeed.com/rc/clk?jk=7e613e94fa9162...
10,AI / ML Engineer,NKU Technologies Pvt.Ltd.,Lahore,"Rs 100,000 - Rs 150,000 a month",We are looking for a Machine Learning/AI Devel...,https://pk.indeed.com/rc/clk?jk=0cc0e25928ad80...
11,Python Developer,Acclivousbyte,Lahore,"From Rs 120,000 a month",The ideal candidate will have strong backend d...,https://pk.indeed.com/rc/clk?jk=4467c1889555a0...
12,Python Developer,NOMADs TECH,Lahore,"Rs 60,000 - Rs 80,000 a month",We are looking for an experienced of 6 - 12 mo...,https://pk.indeed.com/rc/clk?jk=e78dc432ebc831...
13,Data Analyst,The Opus Luxury Residences Hotel,Lahore,"Rs 95,000 - Rs 100,000 a month",We’re seeking a dynamic individual to involve ...,https://pk.indeed.com/rc/clk?jk=035917f26bb7be...
14,Python/SQL Developer,Algo,Lahore,Not specified,Working experience with python.\nWorking with ...,https://pk.indeed.com/rc/clk?jk=c3ba7d76e15bd2...
15,Solution architect,CodeNinja,Lahore,Full-time,Design high-level solution architectures and r...,https://pk.indeed.com/rc/clk?jk=765450c13b6b36...
16,Solution Architect,Techcreatix,Lahore,Full-time,This role requires close collaboration with th...,https://pk.indeed.com/rc/clk?jk=6e4d88e432e06e...
17,Mobile App Developer,Xavor Corporation,Lahore,Full-time,Architect scalable and modular mobile app solu...,https://pk.indeed.com/rc/clk?jk=1c1da1e359e3d0...
18,Sr Solution Architect,AF Recruiter,Lahore,Full-time,Collaborate with development teams to translat...,https://pk.indeed.com/rc/clk?jk=ab6ae0dbbb40e6...
19,Solution Architecht,"VoIPmen Private Limited, Lahore",Lahore,Full-time,Conduct system assessments and provide recomme...,https://pk.indeed.com/rc/clk?jk=05d95b970a310e...
20,Senior Technical Engineer (Electrical),MEP Solutions,Lahore,"Rs 150,000 - Rs 200,000 a month","Coordinate with cross-functional teams, includ...",https://pk.indeed.com/rc/clk?jk=d6e3942ed8aabd...
21,Software Solution Architect,Web Applications & Data Integration Company,Lahore,Full-time,Hands-on participation in the software develop...,https://pk.indeed.com/rc/clk?jk=55bd69bf87643e...
22,Senior Architect,Redwood Information & Technologies,Lahore,"Rs 60,000 - Rs 100,000 a month",Lead architectural design and planning across ...,https://pk.indeed.com/rc/clk?jk=0d6983548a2656...
23,Senior Pre-Sales Solution Architect,Ericsson,Lahore,Not specified,Ensure a smooth transition from pre-sales to d...,https://pk.indeed.com/rc/clk?jk=a0f20ef7528021...
24,System Engineer,VaporVM,Lahore,Not specified,Collaborate with cloud architects to design an...,https://pk.indeed.com/rc/clk?jk=235b3eff083356...
25,AWS DIGITAL SOLUTION ARCHITECT,ITC WORLDWIDE,Lahore,Full-time,Develop and maintain solution architecture by ...,https://pk.indeed.com/rc/clk?jk=a7757e420186fd...
26,Software Engineer,Enghouse,Lahore,Full-time,Collaborate with other engineers and software ...,https://pk.indeed.com/rc/clk?jk=8617066944f270...
27,Solutions Architect,Creative Chaos,Lahore,Full-time,Although a solutions architect is not directly...,https://pk.indeed.com/rc/clk?jk=aa48ef8600d07c...
28,Architect,Urban Tech,Lahore,"Rs 50,000 - Rs 60,000 a month","Deliver compelling project presentations, clea...",https://pk.indeed.com/rc/clk?jk=60497459c7dff0...
29,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
30,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...
31,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
32,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...