In [1]:
import pandas as pd
import os
import pathlib

### Open csv dir and load all csv

In [2]:
def load_data_csv(path):
    if not os.path.exists(path):
        raise ValueError("Error: path does not exist")
    
    try:
        for root, _, files in os.walk(path):
            for f in files:
                if f.endswith(".csv"):
                    yield os.path.join(root, f)
    except Exception as e:
        raise ValueError(f"Error loading files due to: {e}")

In [3]:
try:
    all_dfs = []
    for csv_file in load_data_csv("./csv_dir"):
        df = pd.read_csv(csv_file)
        all_dfs.append(df)
    ads = pd.concat(all_dfs, ignore_index=True)
    print(ads.head())
except Exception as e:
    print(f"error occur load dataset due to: {e}")

                                               title  \
0             Senior Front End Developer / Team Lead
1                           Senior ReactJs Developer
2  Full Stack Software Developer (MERN Stack) (RE...
3                          Full Stack MERN Developer
4                               Junior Web Developer

                                      company location  \
0  Compass Training and Consultancy Pvt. Ltd.   Lahore
1                    Physicians Revenue Group   Lahore
2                                          NR   Lahore
3                                   Technisia   Lahore
4                          Xtraordinary Minds   Lahore

                            salary  \
0  Rs 375,000 - Rs 425,000 a month
1                    Not specified
2   Rs 20,000 - Rs 100,000 a month
3                    Not specified
4                        Full-time

                                         description  \
0  4+ years of professional experience as a front...
1  Review code, enforce standards, and mentor jun...
2  Tailwind CSS / Material-UI / Bootstrap.\nWork ...
3  Ability to manage and lead a team of developer...
4  Collaborate with frontend developers to implem...

                                                 url
0  https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1  https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2  https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3  https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4  https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...

#### Clean dataset

In [4]:
ads

,title,company,location,salary,description,url
0,Senior Front End Developer / Team Lead,Compass Training and Consultancy Pvt. Ltd.,Lahore,"Rs 375,000 - Rs 425,000 a month",4+ years of professional experience as a front...,https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1,Senior ReactJs Developer,Physicians Revenue Group,Lahore,Not specified,"Review code, enforce standards, and mentor jun...",https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2,Full Stack Software Developer (MERN Stack) (RE...,NR,Lahore,"Rs 20,000 - Rs 100,000 a month",Tailwind CSS / Material-UI / Bootstrap.\nWork ...,https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3,Full Stack MERN Developer,Technisia,Lahore,Not specified,Ability to manage and lead a team of developer...,https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4,Junior Web Developer,Xtraordinary Minds,Lahore,Full-time,Collaborate with frontend developers to implem...,https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...
...,...,...,...,...,...,...
190,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
191,Senior Software Engineer (Python),FiveRivers Technologies,Lahore,Full-time,Document API endpoints and create comprehensiv...,https://pk.indeed.com/rc/clk?jk=faf2eaf90bbccc...
192,Senior Backend Developer,RepHero Global,Lahore Gulberg Colony,Full-time,"Collaborate with front-end developers, data sc...",https://pk.indeed.com/rc/clk?jk=2728ac97dbaa69...
193,Sr. Python Developer,Excellence Delivered,Lahore Gulberg Colony,"Rs 200,000 - Rs 300,000 a month",The ideal candidate must have strong Python pr...,https://pk.indeed.com/rc/clk?jk=91ad6073652580...
194,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...

In [5]:
ads.drop_duplicates(subset=['title', 'company', 'location', 'description','url'], inplace=True)
ads.dropna(inplace=True)
ads

,title,company,location,salary,description,url
0,Senior Front End Developer / Team Lead,Compass Training and Consultancy Pvt. Ltd.,Lahore,"Rs 375,000 - Rs 425,000 a month",4+ years of professional experience as a front...,https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1,Senior ReactJs Developer,Physicians Revenue Group,Lahore,Not specified,"Review code, enforce standards, and mentor jun...",https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2,Full Stack Software Developer (MERN Stack) (RE...,NR,Lahore,"Rs 20,000 - Rs 100,000 a month",Tailwind CSS / Material-UI / Bootstrap.\nWork ...,https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3,Full Stack MERN Developer,Technisia,Lahore,Not specified,Ability to manage and lead a team of developer...,https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4,Junior Web Developer,Xtraordinary Minds,Lahore,Full-time,Collaborate with frontend developers to implem...,https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...
...,...,...,...,...,...,...
190,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
191,Senior Software Engineer (Python),FiveRivers Technologies,Lahore,Full-time,Document API endpoints and create comprehensiv...,https://pk.indeed.com/rc/clk?jk=faf2eaf90bbccc...
192,Senior Backend Developer,RepHero Global,Lahore Gulberg Colony,Full-time,"Collaborate with front-end developers, data sc...",https://pk.indeed.com/rc/clk?jk=2728ac97dbaa69...
193,Sr. Python Developer,Excellence Delivered,Lahore Gulberg Colony,"Rs 200,000 - Rs 300,000 a month",The ideal candidate must have strong Python pr...,https://pk.indeed.com/rc/clk?jk=91ad6073652580...
194,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...

### Markdown

In [6]:
ads.to_csv('cleaned_job_listings.csv', index=False)

In [8]:
from scrap_ucdv2 import WebScraper

ws = WebScraper() 

df=ws.dataset_comparison()

✅ Config loaded and validated successfully!

AttributeError: 'WebScraper' object has no attribute 'dataset_comparison'

In [ ]:
df

,title,company,location,salary,description,url
0,Senior Front End Developer / Team Lead,Compass Training and Consultancy Pvt. Ltd.,Lahore,"Rs 375,000 - Rs 425,000 a month",4+ years of professional experience as a front...,https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1,Senior ReactJs Developer,Physicians Revenue Group,Lahore,Not specified,"Review code, enforce standards, and mentor jun...",https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2,Full Stack Software Developer (MERN Stack) (RE...,NR,Lahore,"Rs 20,000 - Rs 100,000 a month",Tailwind CSS / Material-UI / Bootstrap.\nWork ...,https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3,Full Stack MERN Developer,Technisia,Lahore,Not specified,Ability to manage and lead a team of developer...,https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4,Junior Web Developer,Xtraordinary Minds,Lahore,Full-time,Collaborate with frontend developers to implem...,https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...
5,Trainee Software Engineer,Avanceon MEA,Lahore,Not specified,Work closely with senior developers to create ...,https://pk.indeed.com/rc/clk?jk=2aeceb36fa9380...
6,Frontend Developer,2BTech,Lahore,"Rs 60,000 - Rs 80,000 a month","Collaborate with backend developers, designers...",https://pk.indeed.com/rc/clk?jk=a0e71f3c1d4957...
7,Sr. Full Stack .Net Developer,Hazen Technologies Inc.,Lahore,Full-time,The ideal candidate will be responsible for de...,https://pk.indeed.com/rc/clk?jk=c8e57566604ed6...
8,.Net Developer,Hazen Technologies Inc.,Lahore,Not specified,"Net Developer, you will be responsible for des...",https://pk.indeed.com/rc/clk?jk=042db5eea79d52...
9,Senior Software Engineer (Frontend Heavy),TechSea,Lahore New University Campus,Full-time,"You will work closely with CTO, Product, Opera...",https://pk.indeed.com/rc/clk?jk=644ae522965642...
10,PHP Laravel Developer Intern,Solutions Wave,Lahore,Not specified,To join internship program you must have basic...,https://pk.indeed.com/rc/clk?jk=97e3d039772ab3...
11,Full Stack .Net Developer,Hazen Technologies Inc.,Lahore,Not specified,NET Developer with expertise in ReactJS to joi...,https://pk.indeed.com/rc/clk?jk=b327e8cd1a2286...
12,Senior Java Developer – Team Lead,Contour Software,Lahore,Full-time,"Work closely with other team members, includin...",https://pk.indeed.com/rc/clk?jk=d7dc854807097a...
13,Principal/ Staff Software Consultant - Java+Re...,Fulcrum Pvt Ltd,Lahore,Full-time,We are on the look-out for Senior Full Stack J...,https://pk.indeed.com/rc/clk?jk=ea05aa5fbfc90d...
14,Python Developer Intern - AI Bot (Whisper + Vo...,"VoIPmen Private Limited, Lahore",Lahore,"Rs 30,000 - Rs 40,000 a month","VoipMen is building a cutting-edge, real-time ...",https://pk.indeed.com/rc/clk?jk=9876d37fe418cb...
15,Data Science Intern,Learners.ai LLC,Lahore,"Rs 50,000 a month",Collaborate proactively with various team memb...,https://pk.indeed.com/rc/clk?jk=f89a5fface7c28...
16,Business Intelligence (Power BI),HR Professional,Lahore,"Rs 200,000 - Rs 295,000 a month",We're looking for a Business Intelligence (BI)...,https://pk.indeed.com/rc/clk?jk=7e613e94fa9162...
17,Python Developer,Stackup Solutions,Lahore,Full-time,The ideal candidate will be responsible for bu...,https://pk.indeed.com/rc/clk?jk=fb9e4637cd70e1...
18,AI Intern,Acclivousbyte,Lahore,"From Rs 30,000 a month","In this role, you will contribute to developin...",https://pk.indeed.com/rc/clk?jk=b5ca242e3500a3...
19,Python Developer,Broadstone technologies,Lahore,"Rs 50,000 - Rs 150,000 a month",Strong grasp of algorithms and core foundation...,https://pk.indeed.com/rc/clk?jk=e47c8442062585...
20,Data Scientist Internship,DevFUM,Lahore,"Rs 25,000 - Rs 30,000 a month",Devfum leverages a specialized blend of web te...,https://pk.indeed.com/rc/clk?jk=e6046c643e517f...
21,Python Developer,NOMADs TECH,Lahore,"Rs 60,000 - Rs 80,000 a month",We are looking for an experienced of 6 - 12 mo...,https://pk.indeed.com/rc/clk?jk=e78dc432ebc831...
22,Junior Full Stack Developer,Smart Computing Private Limited,Lahore,"Rs 54,000 - Rs 72,000 a month",Reports to:* Technical Lead/Engineering Manage...,https://pk.indeed.com/rc/clk?jk=124ec35fd08305...
23,Python Developer,EpazzTech,Lahore,Not specified,"Expertise in Django Framework (Python Web), Py...",https://pk.indeed.com/rc/clk?jk=7a7be53aeed5a3...
24,Junior AI Engineer,Contrive Solutions,Lahore,Not specified,The ideal candidate will work on developing AI...,https://pk.indeed.com/rc/clk?jk=af50d53f2dfc0d...
25,Python/Django Developer,InvoZone,Lahore,Full-time,Lead a team of software engineers.\nMentor tea...,https://pk.indeed.com/rc/clk?jk=4eda7b470d06b7...
26,DevOps Engineer,ZAPTA TECHNOLOGIES,Lahore,Full-time,"Design, implement, and manage scalable, secure...",https://pk.indeed.com/rc/clk?jk=af4cc94a733f26...
27,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Design, develop, and maintain backend servic...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
28,Python Developer,PureLogics,Lahore,"Rs 200,000 - Rs 300,000 a month",The ideal candidate will have a solid backgrou...,https://pk.indeed.com/rc/clk?jk=60db15ff401d09...
29,Solution Architect,Techcreatix,Lahore,Full-time,This role requires close collaboration with th...,https://pk.indeed.com/rc/clk?jk=6e4d88e432e06e...
30,Sr Solution Architect,AF Recruiter,Lahore,Full-time,Collaborate with development teams to translat...,https://pk.indeed.com/rc/clk?jk=ab6ae0dbbb40e6...
31,AWS DIGITAL SOLUTION ARCHITECT,ITC WORLDWIDE,Lahore,Full-time,Develop and maintain solution architecture by ...,https://pk.indeed.com/rc/clk?jk=a7757e420186fd...
32,Solution Architecht,"VoIPmen Private Limited, Lahore",Lahore,Full-time,Conduct system assessments and provide recomme...,https://pk.indeed.com/rc/clk?jk=05d95b970a310e...
33,Architect,Urban Tech,Lahore,"Rs 50,000 - Rs 60,000 a month","Deliver compelling project presentations, clea...",https://pk.indeed.com/rc/clk?jk=60497459c7dff0...
34,Senior WordPress Developer,GID Enterprises,Lahore Ferozepur Road,"Rs 80,000 - Rs 130,000 a month",Architect and implement directory/listing and ...,https://pk.indeed.com/rc/clk?jk=31f9775a2f6194...
35,Senior WordPress and Shopify Developer,SMADA CONSTRUCTION AND ARCHITECTS,Lahore,"Rs 100,000 - Rs 125,000 a month",Senior WordPress & Shopify Developer – Night S...,https://pk.indeed.com/rc/clk?jk=2c07a9c287170b...
36,Backend Developer,Core Growth Pvt Ltd,Lahore,"Rs 90,000 - Rs 130,000 a month","Design and implement scalable, high-performanc...",https://pk.indeed.com/rc/clk?jk=fcdf4d6643c2d8...
37,Principle Architect,International Petrochemical,Lahore,Not specified,Develop innovative and sustainable design solu...,https://pk.indeed.com/rc/clk?jk=c22ddfa315b922...
38,System & Network Engineer,GCS Information Technology Solutions,Lahore,Not specified,Maintain accurate documentation for all proced...,https://pk.indeed.com/rc/clk?jk=1330fe60a67e48...
39,Area Manager – Construction Chemicals,1 Solution Consulting,Lahore,"Up to Rs 200,000 a month","Collaborate with consultants, contractors, arc...",https://pk.indeed.com/rc/clk?jk=621d6189ab3019...
40,Solution Architects & Integration Experts – Te...,Suave Solutions,Lahore Gpo,"From Rs 300,000 a month",Work closely with product and delivery teams t...,https://pk.indeed.com/rc/clk?jk=a144ca5302f34b...
41,Project Manager,University of Management and Technology,Lahore,Not specified,"Coordinate with architects, engineers, and con...",https://pk.indeed.com/rc/clk?jk=135c8e0aefb185...
42,Senior Full Stack Developer - Technical Leader...,Ebridge Technologies,Lahore,"Rs 150,000 - Rs 350,000 a month","Architect and integrate APIs, third-party serv...",https://pk.indeed.com/rc/clk?jk=6953085643a28c...
43,Senior Backend Developer,RepHero Global,Lahore Gulberg Colony,Full-time,"Collaborate with front-end developers, data sc...",https://pk.indeed.com/rc/clk?jk=2728ac97dbaa69...
44,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
45,Sr. Python Developer,Excellence Delivered,Lahore Gulberg Colony,"Rs 200,000 - Rs 300,000 a month",The ideal candidate must have strong Python pr...,https://pk.indeed.com/rc/clk?jk=91ad6073652580...
46,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...
47,Senior Software Engineer (Python),FiveRivers Technologies,Lahore,Full-time,Document API endpoints and create comprehensiv...,https://pk.indeed.com/rc/clk?jk=faf2eaf90bbccc...
48,Senior Backend Developer,RepHero Global,Lahore Gulberg Colony,Full-time,"Collaborate with front-end developers, data sc...",https://pk.indeed.com/rc/clk?jk=2728ac97dbaa69...
49,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
50,Sr. Python Developer,Excellence Delivered,Lahore Gulberg Colony,"Rs 200,000 - Rs 300,000 a month",The ideal candidate must have strong Python pr...,https://pk.indeed.com/rc/clk?jk=91ad6073652580...
51,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...
52,Senior Software Engineer (Python),FiveRivers Technologies,Lahore,Full-time,Document API endpoints and create comprehensiv...,https://pk.indeed.com/rc/clk?jk=faf2eaf90bbccc...

In [9]:
from scrap_ucdv2 import WebScraper

ws=WebScraper()

✅ Config loaded and validated successfully!

In [10]:
data=ws.get_combine_data()

In [11]:
data

,title,company,location,salary,description,url
0,Senior Front End Developer / Team Lead,Compass Training and Consultancy Pvt. Ltd.,Lahore,"Rs 375,000 - Rs 425,000 a month",4+ years of professional experience as a front...,https://pk.indeed.com/rc/clk?jk=faf308b96fbe6b...
1,Senior ReactJs Developer,Physicians Revenue Group,Lahore,Not specified,"Review code, enforce standards, and mentor jun...",https://pk.indeed.com/rc/clk?jk=3ac9497617f219...
2,Full Stack Software Developer (MERN Stack) (RE...,NR,Lahore,"Rs 20,000 - Rs 100,000 a month",Tailwind CSS / Material-UI / Bootstrap.\nWork ...,https://pk.indeed.com/rc/clk?jk=179ab1d6485238...
3,Full Stack MERN Developer,Technisia,Lahore,Not specified,Ability to manage and lead a team of developer...,https://pk.indeed.com/rc/clk?jk=88f20e1e7ec5dd...
4,Junior Web Developer,Xtraordinary Minds,Lahore,Full-time,Collaborate with frontend developers to implem...,https://pk.indeed.com/rc/clk?jk=3562f396cfb11a...
...,...,...,...,...,...,...
190,Python Developer,Cyber Evangelists,Lahore,"Rs 100,000 - Rs 300,000 a month","* Collaborate with frontend developers, produc...",https://pk.indeed.com/rc/clk?jk=b5351200ebcb3c...
191,Senior Software Engineer (Python),FiveRivers Technologies,Lahore,Full-time,Document API endpoints and create comprehensiv...,https://pk.indeed.com/rc/clk?jk=faf2eaf90bbccc...
192,Senior Backend Developer,RepHero Global,Lahore Gulberg Colony,Full-time,"Collaborate with front-end developers, data sc...",https://pk.indeed.com/rc/clk?jk=2728ac97dbaa69...
193,Sr. Python Developer,Excellence Delivered,Lahore Gulberg Colony,"Rs 200,000 - Rs 300,000 a month",The ideal candidate must have strong Python pr...,https://pk.indeed.com/rc/clk?jk=91ad6073652580...
194,Lead Django + AI Developer,FalconXoft,Lahore,Full-time,"As a Lead AI + Django developer, you will be r...",https://pk.indeed.com/rc/clk?jk=292ac7d03ada51...

In [ ]:
tdata=[
  {
    "title": "Junior Web Developer",
    "company": "Xtraordinary Minds",
    "location": "Lahore",
    "salary": None,
    "description": "Collaborate with frontend developers to implement user-facing features. Job Type:* Full-time (On-site). Shift:* 6:00 PM – 4:00 AM (Saturday working, Sunday off)…",
    "url": None
  },
  {
    "title": "Senior React JS Developer",
    "company": "Zweidevs Pvt Ltd",
    "location": "Lahore",
    "salary": "Rs 120,000 - Rs 150,000 a month",
    "description": "You will also ensure that these components and the overall application are robust and easy to maintain. Must have expertise in React Native.",
    "url": None
  },
  {
    "title": "MERN Stack Developer",
    "company": "Crewlogix Technologies",
    "location": "Lahore",
    "salary": None,
    "description": "The ideal candidate will have 4–6 years of hands-on experience building responsive web applications, RESTful APIs, and scalable back-end systems.",
    "url": None
  },
  {
    "title": "Sr. Python Developer",
    "company": "Excellence Delivered",
    "location": "Lahore Gulberg Colony",
    "salary": "Rs 200,000 - Rs 300,000 a month",
    "description": "The ideal candidate must have strong Python programming expertise, hands-on experience building AI/ML applications from the ground up, and the ability to…",
    "url": "https://pk.indeed.com/rc/clk?jk=91ad607365258092&bb=c4dJHOEGY8__X6qjelBDkW5o5yOk3S0KuDq0hz9BfHmpREM3B6pfQg4RteBnppP7-O9BYS3tmQNIz9NDYFdDhkrZVJ7cyUI2mLIuAB03-noGtPGXr1-zvJwtwjKQMYQh&xkcb=SoAe67M3ycxa9JgNmz0KbzkdCdPP&fccid=4dc1d62cbbc24017&cmp=Excellence-Delivered&ti=Python+Developer&vjs=3"
  },
  {
    "title": "Full Stack Developer",
    "company": "Xavor Corporation",
    "location": "Lahore",
    "salary": None,
    "description": "The ideal candidate will have deep expertise in developing APIs and microservices, implementing caching strategies, and working within a DevOps-driven AWS environment.",
    "url": None
  },
  {
    "title": "Technical Lead",
    "company": "Jerrax",
    "location": "Lahore",
    "salary": "From Rs 150,000 a month",
    "description": "As a Technical Lead at Jerrax, you will play a critical role in architecting and overseeing the development of cutting-edge solutions.",
    "url": None
  },
  {
    "title": "Senior Software Engineer - Laravel",
    "company": "Dubizzle Labs",
    "location": "Lahore",
    "salary": None,
    "description": "Troubleshoot, test, and maintain the core product software and databases to ensure strong optimization and functionality. Experience working with Strapi CMS.",
    "url": None
  },
  {
    "title": "MERN Stack Developer",
    "company": "NKU Technologies Pvt.Ltd.",
    "location": "Lahore",
    "salary": "From Rs 110,000 a month",
    "description": "Develop and maintain web applications using the MERN stack, including front-end and back-end components. Design and implement RESTful APIs for seamless data integration.",
    "url": None
  },
  {
    "title": "Frontend + vuejs Developer",
    "company": "ZEREFLAB",
    "location": "Lahore",
    "salary": "From Rs 130,000 a month",
    "description": "Determining the structure and design of web pages. Ensuring user experience determines design choices. Developing features to enhance the user experience.",
    "url": None
  },
  {
    "title": "Data Warehousing Developer",
    "company": "HR Professional",
    "location": "Lahore",
    "salary": " ",
    "description": "We are looking for an experienced Data Warehousing Developer specializing in ETL pipelines and columnar databases (e.g., ClickHouse, Amazon Redshift,…",
    "url": " "
  },
  {
    "title": "Senior React Native Developer",
    "company": "Stackup Solutions",
    "location": "Lahore",
    "salary": None,
    "description": "Build and maintain cross-platform mobile apps using React Native (iOS & Android). Implement features like chat, audio/video calls, push notifications, and social integrations.",
    "url": None
  },
  {
    "title": "Senior Software Engineer - MERN",
    "company": "stackaxiom",
    "location": "Lahore",
    "salary": "Rs 200,000 - Rs 300,000 a month",
    "description": "Your expertise in Nest.js along with Node.js, Express.js, React.js, Next.js, MongoDB, and TypeScript will be key in driving the successful development of applications.",
    "url": None
  },
  {
    "title": "Node Js Developer",
    "company": "VIION Technology",
    "location": "Lahore",
    "salary": None,
    "description": "Minimum 1 year experience in Node. Knowledge of best practices for the full software development life cycle, including coding standards, code reviews, source control management, etc.",
    "url": None
  },
  {
    "title": "MERN Stack Developer",
    "company": "Solutionsloft",
    "location": "Lahore",
    "salary": "From Rs 170,000 a month",
    "description": "The successful candidate will be responsible for developing and maintaining web applications using the MERN (MongoDB, Express.js, React.js, Node.js) stack.",
    "url": None
  },
  {
    "title": "Vue.Js Developer",
    "company": "Appsians It Solution",
    "location": "Lahore",
    "salary": None,
    "description": "We are looking for a talented and detail-oriented Frontend Developer with proven experience in building responsive and interactive user interfaces using Vue.js.",
    "url": None
  }
]

In [92]:
def check_duplicate(job, df_existing):
    # Create a unique identifier (tuple) for the job based on key fields
    job_identifier = (
        job["title"],
        job["company"],
        job["location"],
        job["description"],
        job["url"]
    )
    # Convert the DataFrame into a set of unique job identifiers (tuples)
    df_existing_identifiers = set(df_existing[['title', 'company', 'location', 'description', 'url']].apply(tuple, axis=1))

    return job_identifier in df_existing_identifiers

In [93]:
def filter_unique_jobs(job_data_list, df_existing):
    unique_jobs = []
    for job in job_data_list:
        if   check_duplicate(job, df_existing):
            unique_jobs.append(job)
    return unique_jobs

In [95]:
filter_unique_jobs(tdata,data)

[{'title': 'Sr. Python Developer',
  'company': 'Excellence Delivered',
  'location': 'Lahore Gulberg Colony',
  'salary': 'Rs 200,000 - Rs 300,000 a month',
  'description': 'The ideal candidate must have strong Python programming expertise, hands-on experience building AI/ML applications from the ground up, and the ability to…',
  'url': 'https://pk.indeed.com/rc/clk?jk=91ad607365258092&bb=c4dJHOEGY8__X6qjelBDkW5o5yOk3S0KuDq0hz9BfHmpREM3B6pfQg4RteBnppP7-O9BYS3tmQNIz9NDYFdDhkrZVJ7cyUI2mLIuAB03-noGtPGXr1-zvJwtwjKQMYQh&xkcb=SoAe67M3ycxa9JgNmz0KbzkdCdPP&fccid=4dc1d62cbbc24017&cmp=Excellence-Delivered&ti=Python+Developer&vjs=3'},
 {'title': 'Data Warehousing Developer',
  'company': 'HR Professional',
  'location': 'Lahore',
  'salary': ' ',
  'description': 'We are looking for an experienced Data Warehousing Developer specializing in ETL pipelines and columnar databases (e.g., ClickHouse, Amazon Redshift,…',
  'url': 'https://pk.indeed.com/rc/clk?jk=a1b50b15eccf449d&bb=orFnlXe5ElebPHm8hiOAhl6gQF4JZv38Jti61WNB4dSzRG8gsymX6bmO2-nolAIRklVSK6Yxiy3k-cMwM5B-FR-k7zMkoyAN-1hSgQS4bYflfyJEK_a4cqIbO91ZfLZ2&xkcb=SoCT67M3ycxDJ2xCGh0MbzkdCdPP&fccid=4c2bf637c99bf9ac&cmp=HR-Professional&ti=Data+Warehouse+Engineer&vjs=3'}]

In [ ]:
for d in tdata:
    print(d)

{'title': 'Junior Web Developer', 'company': 'Xtraordinary Minds', 'location': 'Lahore', 'salary': None, 'description': 'Collaborate with frontend developers to implement user-facing features. Job Type:* Full-time (On-site). Shift:* 6:00 PM – 4:00 AM (Saturday working, Sunday off)…', 'url': None}